pathfinder_special_juggernaut_wind_breathing_dummy = class({})
LinkLuaModifier( "modifier_pathfinder_special_juggernaut_wind_breathing_dummy", "heroes/juggernaut/modifier_pathfinder_special_juggernaut_wind_breathing_dummy", LUA_MODIFIER_MOTION_NONE )

function pathfinder_special_juggernaut_wind_breathing_dummy:GetIntrinsicModifierName()
	return "modifier_pathfinder_special_juggernaut_wind_breathing_dummy"
end
